### PR TITLE
Fix memory leak on client disconnect

### PR DESCRIPTION
**Pull request by ViRb3**
I've been profiling All the Mods 9, a heavy modpack with 400+ mods, to try and reduce the most impactful memory leaks. I discovered that the cache object in BeeIngredient transiently holds onto a reference of ClientLevel, which weighs over 300MB. Since the cache is never unloaded, every rejoin of the server adds another 300MB of consumed RAM, quickly making the game very laggy.

Screenshot 2024-05-13 at 23 50 08

My proposed fix is not particularly beautiful, but I can confirm it works. Since WeakHashMap only holds a weak reference to the key, and that one won't expire, we need to manually wrap the value in WeakReference.

If you have any better approaches, please feel free to implement them. Thanks!

### CODE REVIEW

**Comment by JaisDK** [comment]
Thank you for the investigations. I’ll take a good look at it tomorrow.

**Comment by ViRb3** [comment]
On second thought, I'm not sure my fix addresses the root cause of the issue here. On a singleplayer world with just this mod and JEI installed, I can't seem to reproduce. How exactly is BeeIngredient used?

**Comment by JaisDK** [comment]
GT has a pretty aggressive recipe cache, maybe it's involved.

The BeeIngredient is used both in recipe stuff and to show the bee in JEI as a rendered entity hence why I keep a cache of entities.

**Comment by JaisDK** [comment]
I implemented the changes as well as fixed another location with mem leaks

**Pull request closed without merging**
