### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by Alepod**
now on **dev**

### CODE REVIEW

**Comment by JaisDK** [comment]
@Alepod I realized that the ru translation file did not have all the new string inside. I've updated the file and added translations from Google Translate to it, can you run through it again?
If you are interested, I just set up a translation project here https://poeditor.com/projects/view?id=410923 so I can better manage translations. I can add you to the Russian translation if you want.

**Comment by Alepod** [comment]
Okay, wait a bit

**Comment by Alepod** [comment]
@JaisDK Any way to fix link / join translation project?

**Comment by JaisDK** [comment]
I think I got you added

**Pull request merged**
